# Site settings
title: Model Assisted Root Image Analysis - MARIA
email: guillaume.lobet@ulg.ac.be
description: 
  The website presents and introduce MARIA, a Model Assisted Root Image Analysis pipeline. 
baseurl: "/MARIAProject" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: guillaumelobet
github_username:  guillaumelobet

# Build settings
markdown: kramdown
